FROM grafana/grafana:latest

RUN set -ex \
  && mkdir -p /tmp/provisioning/plugins \
  && mkdir -p /tmp/provisioning/dashboards \
  && mkdir -p /tmp/provisioning/notifiers \
  && mkdir -p /tmp/provisioning/datasources \
  && mkdir -p /tmp/config

COPY --chmod="644" ["files/grafana.ini","/tmp/config/grafana.ini"]
COPY --chmod="644" ["files/grafana.ds.yml","/tmp/provisioning/datasources/datasources.yml"]
