---
version: '3.8'

volumes:
  minio:

services:

  prometheus:
    image: local/prometheus:dev
    build:
      dockerfile: Dockerfile.prometheus
      context: .
    deploy:
      resources:
        limits:
          memory: 100M
    ports: ["9090:9090"]
    command: ["--config.file=/prometheus.yaml"]

  minio:
    image: local/minio:dev
    #user: root
    build:
      dockerfile: Dockerfile.minio
      context: .
    deploy:
      resources:
        limits:
          memory: 150M
    ports: ["9001:9001"]
    volumes:
    - type: volume
      source: minio
      target: /exports
    environment:
      #MINIO_BROWSER: 'off'
      MINIO_ROOT_USER: lokiadmin
      MINIO_ROOT_PASSWORD: lokiadmin
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_PROMETHEUS_URL: http://prometheus:9090
      MINIO_PROMETHEUS_JOB_ID: minio
    command: ["server","/exports","--console-address=:9001"]

  loki:
    image: local/loki:dev
    user: root
    depends_on: ["minio"]
    build:
      dockerfile: Dockerfile.loki
      context: .
    deploy:
      resources:
        limits:
          memory: 100M
    command: ["-config.file=/loki.yaml","-config.expand-env=true","-log-config-reverse-order"]
  
  fluentbit:
    image: local/fluentbit:dev
    depends_on: ["loki"]
    build:
      dockerfile: Dockerfile.fluentbit
      context: .
    deploy:
      resources:
        limits:
          memory: 50M
    entrypoint: /fluent-bit/bin/fluent-bit
    command: ["-c", "/fluentbit.conf"]

  grafana:
    image: local/grafana:dev
    depends_on: ["loki","prometheus"]
    build:
      dockerfile: Dockerfile.grafana
      context: .
    deploy:
      resources:
        limits:
          memory: 100M
    ports: ["3000:3000"]
    environment:
      GF_PATHS_CONFIG: /tmp/config/grafana.ini
      GF_PATHS_PROVISIONING: /tmp/provisioning
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
