---
global:
  scrape_interval: 10s

scrape_configs:

- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: [prometheus:9090]

- job_name: grafana
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: [grafana:3000]

- job_name: loki
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: [loki:3100]

- job_name: fluentbit
  metrics_path: /api/v1/metrics/prometheus
  scheme: http
  static_configs:
  - targets: [fluentbit:2020]

- job_name: minio
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: [minio:9000]
